Change the way process killing is done

diff --git a/catnip b/catnip
--- a/catnip
+++ b/catnip
@@ -17,9 +17,10 @@ function loadPackage {
   DEPLOY_START=
   if [ -d $CATNIP_HOME/$1 ] && [ -f $CATNIP_HOME/$1/package.cat ]; then
     . $CATNIP_HOME/$1/package.cat
+    return 1
   else
     echo "Package not found"
-    exit 1
+    return 0
   fi
 }
 
@@ -35,16 +36,19 @@ function loadBuildNumber {
 
 function checkRunning {
   [ -f $CATNIP_HOME/$1/catnip.pid ] || return 0
-  PID=$(cat $CATNIP_HOME/$1/catnip.pid 2> /dev/null)
+  PID1=$(cat $CATNIP_HOME/$1/catnip.pid 2> /dev/null)
+  ps -p $PID1 > /dev/null 2>&1
   if [ $? -eq 0 ]; then
-    ps -p $PID > /dev/null 2>&1
+    [ -f $CATNIP_HOME/$1/process.pid ] || return 1
+    PID2=$(cat $CATNIP_HOME/$1/process.pid 2> /dev/null)
+    ps -p $PID2 > /dev/null 2>&1
     if [ $? -eq 0 ]; then
-      return 1
+      return 2 # Process and cn-forever running
     else
-      return 0
+      return 1 # ONly cn-forever running ( process crashed )
     fi
   else
-    return 0
+    return 0 # Nothing running
   fi
 }
 
@@ -90,6 +94,9 @@ function deploy {
     if $DEPLOY_START; then
       stop $1
       start $1
+      if [ $? -ne 0 ]; then
+        exit $?
+      fi
     fi
 
     END_TIME=$(date +%s.%N)
@@ -112,7 +119,11 @@ function list {
     PACKAGE_NAME=$(basename $dir)
     checkRunning $PACKAGE_NAME
     if [ $? -ne 0 ]; then
-      echo "  $PACKAGE_NAME"
+      if [ $? -eq 2 ]; then
+        echo "  $PACKAGE_NAME"
+      else
+        echo "  $PACKAGE_NAME [crashed]"
+      fi
       NOTFOUND=false
     fi
   done
@@ -133,7 +144,7 @@ function autostart {
   for dir in `find $CATNIP_HOME -maxdepth 1 -mindepth 1 -type d`; do
     if [ -f $dir/package.cat ]; then
       PACKAGE_NAME=$(basename $dir)
-      loadPackage $PACKAGE_NAME
+      loadPackage $PACKAGE_NAME || continue
       $AUTO_START && start $PACKAGE_NAME
     fi
   done
@@ -143,7 +154,7 @@ function stopall {
   for dir in `find $CATNIP_HOME -maxdepth 1 -mindepth 1 -type d`; do
     if [ -f $dir/package.cat ]; then
       PACKAGE_NAME=$(basename $dir)
-      loadPackage $PACKAGE_NAME
+      loadPackage $PACKAGE_NAME || continue
       stop $PACKAGE_NAME
     fi
   done
@@ -152,18 +163,18 @@ function stopall {
 function start {
   [ -z "$PACKAGE_START" ] && return
   cd $CATNIP_HOME/$1
+  echo ""
+  echo " --- $1: starting up --- "
   if ! [ -d ./package ]; then
     echo "$1 has no source!"
-    return
+    return 3
   else
     checkRunning $1
     if [ $? -ne 0 ]; then
       echo "$1 is already running."
-      return
+      return 0
     fi
   fi
-  echo ""
-  echo " --- $1: starting up --- "
   echo " --- $1: starting up --- `date` --- " >> catnip.log
   touch catnip.pid
   chmod 666 catnip.pid
@@ -171,11 +182,15 @@ function start {
   sudo -u $EXEC_USER env CATNIP=true $PACKAGE_ENV nohup $CATNIP_BIN/cn-forever $PACKAGE_START >> $CATNIP_HOME/$1/catnip.log 2>&1 &
   sleep 1
   checkRunning $1
-  if [ $? -ne 0 ]; then
+  if [ $? -eq 2 ]; then
     echo "Started Successfully"
+    return 0
+  elif [ $? -eq 1 ]; then
+    echo "Started but crashed"
+    return 1
   else
-    echo "Failed to start process"
-    exit 1
+    echo "Failed to start"
+    return 2
   fi
 }
 
@@ -188,17 +203,19 @@ function stop {
   checkRunning $1
   if [ $? -ne 0 ]; then
     echo " --- $1: stopping --- `date` --- " >> catnip.log
-    sudo -u $EXEC_USER kill $PID
+    sudo -u $EXEC_USER kill $PID1
+    timeout 2 bash -c "while true; do [ -f catnip.pid ] || break; done"
     checkRunning $1
     if [ $? -ne 0 ]; then
       echo "Failed to stop process"
-      exit 1
+      return 1
     else
       echo "Stopped $1"
-      rm -f catnip.pid
+      return 0
     fi
   else
     echo "Process not running"
+    return 0
   fi
 }
 
@@ -228,10 +245,10 @@ function sync {
   echo " --- $1: synchronizing --- "
   if [ -z "$REPO_TYPE" ]; then
     echo "Missing repository type"
-    exit 1
+    return 1
   elif [ -z "$REPO_ORIGIN" ]; then
     echo "Missing repository origin"
-    exit 1
+    return 1
   fi
   case $REPO_TYPE in
     git )
@@ -242,7 +259,7 @@ function sync {
       ;;
     * )
       echo "Invalid repository type specified"
-      exit 1
+      return 1
   esac
 }
 
@@ -274,7 +291,7 @@ case $1 in
     ;;
   d|deploy )
     [ -z "$2" ] && usage
-    loadPackage $2
+    loadPackage $2 || exit 1
     deploy $2
     ;;
   list )
@@ -286,26 +303,29 @@ case $1 in
     ;;
   r|restart )
     [ -z "$2" ] && usage
-    loadPackage $2
-    stop $2
+    loadPackage $2 || exit 1
+    stop $2 && exit $?
     start $2
+    exit $?
     ;;
   start )
     [ -z "$2" ] && usage
-    loadPackage $2
+    loadPackage $2 || exit 1
     start $2
+    exit $?
     ;;
   stop )
     [ -z "$2" ] && usage
-    loadPackage $2
+    loadPackage $2 || exit 1
     stop $2
+    exit $?
     ;;
   stopall )
     stopall
     ;;
   sync )
     [ -z "$2" ] && usage
-    loadPackage $2
+    loadPackage $2 || exit 1
     sync $2
     ;;
   * )
