Made sure loadPackage resets the state before loading the next package Consolidated pid file checks into it's own function Added autostart command and AUTO_START option to packages Added DEPLOY_START option to packages Fixed list command to use a non-recursive find Added additional checks on start command

diff --git a/catnip b/catnip
--- a/catnip
+++ b/catnip
@@ -3,6 +3,13 @@
 [ -f /etc/catnip.conf ] && . /etc/catnip.conf
 
 function loadPackage {
+  REPO_TYPE=
+  REPO_ORIGIN=
+  PACKAGE_PREPARE=
+  PACKAGE_START=
+  PACKAGE_ENV=
+  AUTO_START=
+  DEPLOY_START=
   if [ -d $CATNIP_HOME/$1 ] && [ -f $CATNIP_HOME/$1/package.cat ]; then
     . $CATNIP_HOME/$1/package.cat
   else
@@ -19,6 +26,21 @@ function loadBuildNumber {
   fi
   echo "$BUILD_NUMBER" > ./latest.build
   return $BUILD_NUMBER
+}
+
+function checkRunning {
+  [ -f $CATNIP_HOME/$1/catnip.pid ] || return 0
+  PID=$(cat $CATNIP_HOME/$1/catnip.pid 2> /dev/null)
+  if [ $? -eq 0 ]; then
+    ps -p $PID > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+      return 1
+    else
+      return 0
+    fi
+  else
+    return 0
+  fi
 }
 
 function archiveArtifacts {
@@ -60,8 +82,10 @@ function deploy {
     echo "`date`, v$BUILD_NUMBER"
     sync $1
     prepare $1 $BUILD_NUMBER
-    stop $1
-    start $1
+    if $DEPLOY_START; then
+      stop $1
+      start $1
+    fi
 
     END_TIME=$(date +%s.%N)
     DURATION=$(echo "$END_TIME - $START_TIME" | bc)
@@ -80,17 +104,12 @@ function list {
   NOTFOUND=true
   echo ""
   echo "Running packages:"
-  for dir in `find . -type d`
-  do
-    if [ -f $dir/catnip.pid ]; then
-      PID=$(cat $dir/catnip.pid 2> /dev/null)
-      if [ $? -eq 0 ]; then
-        ps -p $PID > /dev/null 2>&1
-        if [ $? -eq 0 ]; then
-          echo "  $(basename $dir)"
-          NOTFOUND=false
-        fi
-      fi
+  for dir in `find . -maxdepth 1 -mindepth 1 -type d`; do
+    PACKAGE_NAME=$(basename $dir)
+    checkRunning $PACKAGE_NAME
+    if [ $? -ne 0 ]; then
+      echo "  $PACKAGE_NAME"
+      NOTFOUND=false
     fi
   done
   if $NOTFOUND; then
@@ -106,26 +125,41 @@ function log {
   fi
 }
 
+function autostart {
+  cd $CATNIP_HOME
+  for dir in `find . -maxdepth 1 -mindepth 1 -type d`; do
+    if [ -f $dir/package.cat ]; then
+      PACKAGE_NAME=$(basename $dir)
+      loadPackage $PACKAGE_NAME
+      $AUTO_START && start $PACKAGE_NAME
+    fi
+  done
+}
+
 function start {
   [ -z "$PACKAGE_START" ] && return
+  cd $CATNIP_HOME/$1
+  if ! [ -d ./package ]; then
+    echo "$1 has no source!"
+    return
+  else
+    checkRunning $1
+    if [ $? -ne 0 ]; then
+      echo "$1 is already running."
+      return
+    fi
+  fi
   echo ""
   echo " --- $1: starting up --- "
-  cd $CATNIP_HOME/$1
   echo " --- $1: starting up --- `date` --- " >> catnip.log
   touch catnip.pid
   chmod 777 catnip.pid
   cd $CATNIP_HOME/$1/package
   sudo -u $EXEC_USER env CATNIP=true $PACKAGE_ENV nohup $CATNIP_BIN/cn-forever $PACKAGE_START >> $CATNIP_HOME/$1/catnip.log 2>&1 &
   sleep 1
-  PID=$(cat $CATNIP_HOME/$1/catnip.pid 2> /dev/null)
-  if [ $? -eq 0 ]; then
-    ps -p $PID > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-      echo "Started Successfully"
-    else
-      echo "Failed to start process"
-      exit 1
-    fi
+  checkRunning $1
+  if [ $? -ne 0 ]; then
+    echo "Started Successfully"
   else
     echo "Failed to start process"
     exit 1
@@ -138,21 +172,17 @@ function stop {
   echo " --- $1: stopping --- "
   cd $CATNIP_HOME/$1
 
-  PID=$(cat ./catnip.pid 2> /dev/null)
-  if [ $? -eq 0 ]; then
-    ps -p $PID > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-      echo " --- $1: stopping --- `date` --- " >> catnip.log
-      sudo -u $EXEC_USER kill $PID
-      ps -p $PID > /dev/null 2>&1
-      if [ $? -eq 0 ]; then
-        echo "Failed to stop process"
-        exit 1
-      else
-        echo "Stopped $1"
-      fi
+  checkRunning $1
+  if [ $? -ne 0 ]; then
+    echo " --- $1: stopping --- `date` --- " >> catnip.log
+    sudo -u $EXEC_USER kill $PID
+    checkRunning $1
+    if [ $? -ne 0 ]; then
+      echo "Failed to stop process"
+      exit 1
     else
-      echo "Process not running"
+      echo "Stopped $1"
+      rm -f catnip.pid
     fi
   else
     echo "Process not running"
@@ -207,6 +237,7 @@ function usage {
   echo "    usage: catnip [action] PACKAGE"
   echo ""
   echo "    actions:"
+  echo "      autostart    execute start for all packages"
   echo "      deploy       synchronize and start/restart PACKAGE"
   echo "      list         list all running packages"
   echo "      log          display the log file for a package"
@@ -223,6 +254,9 @@ if [ `whoami` != $BUILD_USER ]; then
 fi
 
 case $1 in
+  autostart )
+    autostart
+    ;;
   d|deploy )
     [ -z "$2" ] && usage
     loadPackage $2
